CREATE TABLE IF NOT EXISTS bid
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    amount     DECIMAL                                 NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    product_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_bid PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS category
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(30)                             NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS credit_card
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    card_name        VARCHAR(255)                            NOT NULL,
    card_number      VARCHAR(19)                             NOT NULL,
    expiration_month INTEGER                                 NOT NULL,
    expiration_year  INTEGER                                 NOT NULL,
    cvv              INTEGER                                 NOT NULL,
    user_id          BIGINT                                  NOT NULL,
    CONSTRAINT pk_creditcard PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS product
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255)                            NOT NULL,
    description    VARCHAR(255),
    start_price    DECIMAL,
    created_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    auction_start  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    auction_end    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    size           VARCHAR(255),
    color          VARCHAR(255),
    subcategory_id BIGINT                                  NOT NULL,
    user_id        BIGINT                                  NOT NULL,
    CONSTRAINT pk_product PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS product_picture
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    url        VARCHAR(255)                            NOT NULL,
    product_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_productpicture PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS profile
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name       VARCHAR(30)                             NOT NULL,
    last_name        VARCHAR(30)                             NOT NULL,
    email            VARCHAR(255)                            NOT NULL,
    password         VARCHAR(255)                            NOT NULL,
    username         VARCHAR(255)                            NOT NULL,
    birth_date       date                                    NOT NULL,
    phone_number     VARCHAR(255),
    shipping_address VARCHAR(255),
    shipping_city    VARCHAR(255),
    zip_code         VARCHAR(255),
    state            VARCHAR(255),
    country          VARCHAR(255),
    role_id          BIGINT                                  NOT NULL,
    CONSTRAINT pk_profile PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS role
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_role PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS sub_category
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(30)                             NOT NULL,
    category_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_subcategory PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS wish_list
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    product_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_wishlist PRIMARY KEY (id)
);

ALTER TABLE category
    ADD CONSTRAINT uc_11bf5dd4f6db5221aa3d8ee91 UNIQUE (name);

ALTER TABLE role
    ADD CONSTRAINT uc_c3ec6f024c9d52963edb76ef7 UNIQUE (name);

ALTER TABLE profile
    ADD CONSTRAINT uc_profile_email UNIQUE (email);

ALTER TABLE profile
    ADD CONSTRAINT uc_profile_username UNIQUE (username);

ALTER TABLE bid
    ADD CONSTRAINT FK_BID_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (id);

ALTER TABLE bid
    ADD CONSTRAINT FK_BID_ON_USER FOREIGN KEY (user_id) REFERENCES profile (id);

ALTER TABLE credit_card
    ADD CONSTRAINT FK_CREDITCARD_ON_USER FOREIGN KEY (user_id) REFERENCES profile (id);

ALTER TABLE product_picture
    ADD CONSTRAINT FK_PRODUCTPICTURE_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (id);

ALTER TABLE product
    ADD CONSTRAINT FK_PRODUCT_ON_SUBCATEGORY FOREIGN KEY (subcategory_id) REFERENCES sub_category (id);

ALTER TABLE product
    ADD CONSTRAINT FK_PRODUCT_ON_USER FOREIGN KEY (user_id) REFERENCES profile (id);

ALTER TABLE profile
    ADD CONSTRAINT FK_PROFILE_ON_ROLE FOREIGN KEY (role_id) REFERENCES role (id);

ALTER TABLE sub_category
    ADD CONSTRAINT FK_SUBCATEGORY_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES category (id);

ALTER TABLE wish_list
    ADD CONSTRAINT FK_WISHLIST_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (id);

ALTER TABLE wish_list
    ADD CONSTRAINT FK_WISHLIST_ON_USER FOREIGN KEY (user_id) REFERENCES profile (id);