CREATE TABLE IF NOT EXISTS bid
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    amount     DECIMAL                                 NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    product_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_bid PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS category
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(30)                             NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS product
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                VARCHAR(255)                            NOT NULL,
    description         VARCHAR(2000),
    start_price         DECIMAL,
    created_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    auction_start       date                                    NOT NULL,
    auction_end         date                                    NOT NULL,
    size                VARCHAR(255),
    color               VARCHAR(255),
    subcategory_id      BIGINT                                  NOT NULL,
    user_id             BIGINT                                  NOT NULL,
    return_address      VARCHAR(255),
    return_email        VARCHAR(255),
    return_city         VARCHAR(255),
    return_zipcode      VARCHAR(255),
    return_country      VARCHAR(255),
    return_phone_number VARCHAR(255),
    is_paid BOOLEAN,
    CONSTRAINT pk_product PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS product_picture
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    url        VARCHAR(2000)                           NOT NULL,
    product_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_product_picture PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS person
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name       VARCHAR(30)                             NOT NULL,
    last_name        VARCHAR(30)                             NOT NULL,
    email            VARCHAR(255)                            NOT NULL,
    password         VARCHAR(255)                            NOT NULL,
    birth_date       date,
    phone_number     VARCHAR(255),
    shipping_address VARCHAR(255),
    shipping_city    VARCHAR(255),
    zip_code         VARCHAR(255),
    state            VARCHAR(255),
    country          VARCHAR(255),
    role             VARCHAR(255),
    active           BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_person PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS sub_category
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(30)                             NOT NULL,
    category_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_subcategory PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS wish_list
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    product_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_wishlist PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS credit_card
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    card_name        VARCHAR(255)                            NOT NULL,
    card_number      VARCHAR(19)                             NOT NULL,
    expiration_month INTEGER                                 NOT NULL,
    expiration_year  INTEGER                                 NOT NULL,
    cvv              INTEGER                                 NOT NULL,
    user_id          BIGINT                                  NOT NULL,
    CONSTRAINT pk_credit_card PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS category
    ADD CONSTRAINT uc_11bf5dd4f6db5221aa3d8ee91 UNIQUE (name);

ALTER TABLE IF EXISTS product_picture
    ADD CONSTRAINT uc_11bf5d1db2131231aa3d8ee91 UNIQUE (name);

ALTER TABLE IF EXISTS person
    ADD CONSTRAINT uc_person_email UNIQUE (email);

ALTER TABLE IF EXISTS credit_card
    ADD CONSTRAINT FK_CREDIT_CARD_ON_USER FOREIGN KEY (user_id) REFERENCES person (id);

ALTER TABLE IF EXISTS bid
    ADD CONSTRAINT FK_BID_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (id);

ALTER TABLE IF EXISTS bid
    ADD CONSTRAINT FK_BID_ON_USER FOREIGN KEY (user_id) REFERENCES person (id);

ALTER TABLE IF EXISTS product_picture
    ADD CONSTRAINT FK_PRODUCT_PICTURE_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (id);

ALTER TABLE IF EXISTS product
    ADD CONSTRAINT FK_PRODUCT_ON_SUBCATEGORY FOREIGN KEY (subcategory_id) REFERENCES sub_category (id);

ALTER TABLE IF EXISTS product
    ADD CONSTRAINT uc_c2ec1f420c2e12345edb76ef7 UNIQUE (name);

ALTER TABLE IF EXISTS product
    ADD CONSTRAINT FK_PRODUCT_ON_USER FOREIGN KEY (user_id) REFERENCES person (id);

ALTER TABLE IF EXISTS sub_category
    ADD CONSTRAINT FK_SUBCATEGORY_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES category (id);

ALTER TABLE IF EXISTS wish_list
    ADD CONSTRAINT FK_WISHLIST_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (id);

ALTER TABLE IF EXISTS wish_list
    ADD CONSTRAINT FK_WISHLIST_ON_USER FOREIGN KEY (user_id) REFERENCES person (id);