-- Insertion of person
INSERT INTO person (first_name, last_name, birth_date, country, email, password, role, active)
VALUES ('Ahmedin', 'Hasanovic', '2000-02-22', 'Bosna I Hercegovina', 'ahmedinhasanovic2000@gmail.com', '$2a$12$1qbXh50N3q78lZpa4gQ0OOAy37h0F6LuwjVuV/zIp2ejN1YpfYvUe', 'ROLE_USER', true),
       ('Niko', 'Nikic', '2000-02-22', 'Bosna I Hercegovina', 'ahasanovic2@etf.unsa.ba', '$2a$12$1qbXh50N3q78lZpa4gQ0OOAy37h0F6LuwjVuV/zIp2ejN1YpfYvUe', 'ROLE_USER', true);

-- Insertion of categories
INSERT INTO category (name) VALUES
                                ('Women'),
                                ('Men'),
                                ('Kids'),
                                ('Accessories'),
                                ('Home'),
                                ('Art'),
                                ('Computers');

-- Insertion of subcategories
INSERT INTO sub_category (name, category_id) VALUES
                                                 ('Accessories', (SELECT id FROM category c WHERE c.name='Women')),
                                                 ('Bags', (SELECT id FROM category c WHERE c.name='Women')),
                                                 ('Shoes', (SELECT id FROM category c WHERE c.name='Women')),
                                                 ('Accessories', (SELECT id FROM category c WHERE c.name='Men')),
                                                 ('Shoes', (SELECT id FROM category c WHERE c.name='Men')),
                                                 ('Clothes', (SELECT id FROM category c WHERE c.name='Men')),
                                                 ('Toys', (SELECT id FROM category c WHERE c.name='Kids')),
                                                 ('Clothes', (SELECT id FROM category c WHERE c.name='Kids')),
                                                 ('Watches', (SELECT id FROM category c WHERE c.name='Accessories')),
                                                 ('Jewelry', (SELECT id FROM category c WHERE c.name='Accessories')),
                                                 ('Bed & Bath', (SELECT id FROM category c WHERE c.name='Home')),
                                                 ('Kitchenware', (SELECT id FROM category c WHERE c.name='Home')),
                                                 ('Paintings', (SELECT id FROM category c WHERE c.name='Art')),
                                                 ('Sculptures', (SELECT id FROM category c WHERE c.name='Art')),
                                                 ('Laptops', (SELECT id FROM category c WHERE c.name='Computers')),
                                                 ('Peripherals', (SELECT id FROM category c WHERE c.name='Computers'));

-- Insertion of products
SELECT * from product;
INSERT INTO product (name, description, start_price, created_at, auction_start, auction_end, size, color, subcategory_id, user_id) VALUES
                                                                                                                                       ('Black shoes with legs','Note:\nThe Jackets is US standard size, Please choose size as your usual wear\nMaterial: 100% Polyester\nDetachable Liner Fabric: Warm Fleece. Detachable\nFunctional Liner: Skin Friendly, Lightweigt and Warm.\nStand Collar Liner jacket, keep you warm in cold weather.\nZippered Pockets: 2 Zippered Hand Pockets, 2 Zippered Pockets on Chest enough to keep cards or keys) and 1 Hidden Pocket Inside.\nZippered Hand Pockets and Hidden Pocket keep your things secure.\nHumanized Design: Adjustable and Detachable Hood and Adjustable cuff to prevent the wind and water,for a comfortable fit.\n3 in 1 Detachable Design provide more convenience, you can separate the coat and inner as needed, or wear it together. It is suitable for different season and help you adapt to different climates',50,'2024-01-01T01:00:00.000','2024-07-01T01:00:00.000','2024-07-15T01:00:00.000', 'LARGE', 'BLACK', (SELECT sc.id FROM sub_category sc WHERE sc.name='Shoes' AND sc.category_id = (SELECT id FROM category c WHERE c.name='Women')), ((SELECT p.id FROM person p WHERE p.email='ahmedinhasanovic2000@gmail.com'))),
                                                                                                                                       ('Brown man shoes','Note:\nThe Jackets is US standard size, Please choose size as your usual wear\nMaterial: 100% Polyester\nDetachable Liner Fabric: Warm Fleece. Detachable\nFunctional Liner: Skin Friendly, Lightweigt and Warm.\nStand Collar Liner jacket, keep you warm in cold weather.\nZippered Pockets: 2 Zippered Hand Pockets, 2 Zippered Pockets on Chest enough to keep cards or keys) and 1 Hidden Pocket Inside.\nZippered Hand Pockets and Hidden Pocket keep your things secure.\nHumanized Design: Adjustable and Detachable Hood and Adjustable cuff to prevent the wind and water,for a comfortable fit.\n3 in 1 Detachable Design provide more convenience, you can separate the coat and inner as needed, or wear it together. It is suitable for different season and help you adapt to different climates',50,'2024-01-01T02:00:00.000','2024-07-01T01:00:00.000','2024-07-14T01:00:00.000', 'LARGE', 'BLACK', (SELECT sc.id FROM sub_category sc WHERE sc.name='Shoes' AND sc.category_id = (SELECT id FROM category c WHERE c.name='Men')), ((SELECT p.id FROM person p WHERE p.email='ahmedinhasanovic2000@gmail.com'))),
                                                                                                                                       ('White casual shoes','Note:\nThe Jackets is US standard size, Please choose size as your usual wear\nMaterial: 100% Polyester\nDetachable Liner Fabric: Warm Fleece. Detachable\nFunctional Liner: Skin Friendly, Lightweigt and Warm.\nStand Collar Liner jacket, keep you warm in cold weather.\nZippered Pockets: 2 Zippered Hand Pockets, 2 Zippered Pockets on Chest enough to keep cards or keys) and 1 Hidden Pocket Inside.\nZippered Hand Pockets and Hidden Pocket keep your things secure.\nHumanized Design: Adjustable and Detachable Hood and Adjustable cuff to prevent the wind and water,for a comfortable fit.\n3 in 1 Detachable Design provide more convenience, you can separate the coat and inner as needed, or wear it together. It is suitable for different season and help you adapt to different climates',50,'2024-01-01T03:00:00.000','2024-07-01T01:00:00.000','2024-07-13T01:00:00.000', 'LARGE', 'BLACK', (SELECT sc.id FROM sub_category sc WHERE sc.name='Shoes' AND sc.category_id = (SELECT id FROM category c WHERE c.name='Women')), ((SELECT p.id FROM person p WHERE p.email='ahmedinhasanovic2000@gmail.com'))),
                                                                                                                                       ('White sport shoes','Note:\nThe Jackets is US standard size, Please choose size as your usual wear\nMaterial: 100% Polyester\nDetachable Liner Fabric: Warm Fleece. Detachable\nFunctional Liner: Skin Friendly, Lightweigt and Warm.\nStand Collar Liner jacket, keep you warm in cold weather.\nZippered Pockets: 2 Zippered Hand Pockets, 2 Zippered Pockets on Chest enough to keep cards or keys) and 1 Hidden Pocket Inside.\nZippered Hand Pockets and Hidden Pocket keep your things secure.\nHumanized Design: Adjustable and Detachable Hood and Adjustable cuff to prevent the wind and water,for a comfortable fit.\n3 in 1 Detachable Design provide more convenience, you can separate the coat and inner as needed, or wear it together. It is suitable for different season and help you adapt to different climates',50,'2024-01-01T04:00:00.000','2024-07-01T01:00:00.000','2024-07-12T01:00:00.000', 'LARGE', 'BLACK', (SELECT sc.id FROM sub_category sc WHERE sc.name='Shoes' AND sc.category_id = (SELECT id FROM category c WHERE c.name='Women')), ((SELECT p.id FROM person p WHERE p.email='ahmedinhasanovic2000@gmail.com'))),
                                                                                                                                       ('Shoes for occasion','Note:\nThe Jackets is US standard size, Please choose size as your usual wear\nMaterial: 100% Polyester\nDetachable Liner Fabric: Warm Fleece. Detachable\nFunctional Liner: Skin Friendly, Lightweigt and Warm.\nStand Collar Liner jacket, keep you warm in cold weather.\nZippered Pockets: 2 Zippered Hand Pockets, 2 Zippered Pockets on Chest enough to keep cards or keys) and 1 Hidden Pocket Inside.\nZippered Hand Pockets and Hidden Pocket keep your things secure.\nHumanized Design: Adjustable and Detachable Hood and Adjustable cuff to prevent the wind and water,for a comfortable fit.\n3 in 1 Detachable Design provide more convenience, you can separate the coat and inner as needed, or wear it together. It is suitable for different season and help you adapt to different climates',50,'2024-01-01T05:00:00.000','2024-07-01T01:00:00.000','2024-07-11T01:00:00.000', 'LARGE', 'BLACK', (SELECT sc.id FROM sub_category sc WHERE sc.name='Shoes' AND sc.category_id = (SELECT id FROM category c WHERE c.name='Women')), ((SELECT p.id FROM person p WHERE p.email='ahmedinhasanovic2000@gmail.com'))),
                                                                                                                                       ('Shoes for occasion2','Note:\nThe Jackets is US standard size, Please choose size as your usual wear\nMaterial: 100% Polyester\nDetachable Liner Fabric: Warm Fleece. Detachable\nFunctional Liner: Skin Friendly, Lightweigt and Warm.\nStand Collar Liner jacket, keep you warm in cold weather.\nZippered Pockets: 2 Zippered Hand Pockets, 2 Zippered Pockets on Chest enough to keep cards or keys) and 1 Hidden Pocket Inside.\nZippered Hand Pockets and Hidden Pocket keep your things secure.\nHumanized Design: Adjustable and Detachable Hood and Adjustable cuff to prevent the wind and water,for a comfortable fit.\n3 in 1 Detachable Design provide more convenience, you can separate the coat and inner as needed, or wear it together. It is suitable for different season and help you adapt to different climates',50,'2024-01-01T06:00:00.000','2024-07-01T01:00:00.000','2024-07-15T10:00:00.000', 'LARGE', 'BLACK', (SELECT sc.id FROM sub_category sc WHERE sc.name='Shoes' AND sc.category_id = (SELECT id FROM category c WHERE c.name='Women')), ((SELECT p.id FROM person p WHERE p.email='ahmedinhasanovic2000@gmail.com'))),
                                                                                                                                       ('Shoes with box','Note:\nThe Jackets is US standard size, Please choose size as your usual wear\nMaterial: 100% Polyester\nDetachable Liner Fabric: Warm Fleece. Detachable\nFunctional Liner: Skin Friendly, Lightweigt and Warm.\nStand Collar Liner jacket, keep you warm in cold weather.\nZippered Pockets: 2 Zippered Hand Pockets, 2 Zippered Pockets on Chest enough to keep cards or keys) and 1 Hidden Pocket Inside.\nZippered Hand Pockets and Hidden Pocket keep your things secure.\nHumanized Design: Adjustable and Detachable Hood and Adjustable cuff to prevent the wind and water,for a comfortable fit.\n3 in 1 Detachable Design provide more convenience, you can separate the coat and inner as needed, or wear it together. It is suitable for different season and help you adapt to different climates',50,'2024-01-01T01:30:00.000','2024-07-01T01:00:00.000','2024-07-15T09:00:00.000', 'LARGE', 'BLACK', (SELECT sc.id FROM sub_category sc WHERE sc.name='Shoes' AND sc.category_id = (SELECT id FROM category c WHERE c.name='Men')), ((SELECT p.id FROM person p WHERE p.email='ahmedinhasanovic2000@gmail.com'))),
                                                                                                                                       ('Sandals','Note:\nThe Jackets is US standard size, Please choose size as your usual wear\nMaterial: 100% Polyester\nDetachable Liner Fabric: Warm Fleece. Detachable\nFunctional Liner: Skin Friendly, Lightweigt and Warm.\nStand Collar Liner jacket, keep you warm in cold weather.\nZippered Pockets: 2 Zippered Hand Pockets, 2 Zippered Pockets on Chest enough to keep cards or keys) and 1 Hidden Pocket Inside.\nZippered Hand Pockets and Hidden Pocket keep your things secure.\nHumanized Design: Adjustable and Detachable Hood and Adjustable cuff to prevent the wind and water,for a comfortable fit.\n3 in 1 Detachable Design provide more convenience, you can separate the coat and inner as needed, or wear it together. It is suitable for different season and help you adapt to different climates',50,'2024-01-01T01:50:00.000','2024-07-01T01:00:00.000','2024-07-15T08:00:00.000', 'LARGE', 'BLACK', (SELECT sc.id FROM sub_category sc WHERE sc.name='Shoes' AND sc.category_id = (SELECT id FROM category c WHERE c.name='Women')), ((SELECT p.id FROM person p WHERE p.email='ahmedinhasanovic2000@gmail.com'))),
                                                                                                                                       ('Second black shoes','Note:\nThe Jackets is US standard size, Please choose size as your usual wear\nMaterial: 100% Polyester\nDetachable Liner Fabric: Warm Fleece. Detachable\nFunctional Liner: Skin Friendly, Lightweigt and Warm.\nStand Collar Liner jacket, keep you warm in cold weather.\nZippered Pockets: 2 Zippered Hand Pockets, 2 Zippered Pockets on Chest enough to keep cards or keys) and 1 Hidden Pocket Inside.\nZippered Hand Pockets and Hidden Pocket keep your things secure.\nHumanized Design: Adjustable and Detachable Hood and Adjustable cuff to prevent the wind and water,for a comfortable fit.\n3 in 1 Detachable Design provide more convenience, you can separate the coat and inner as needed, or wear it together. It is suitable for different season and help you adapt to different climates',50,'2024-01-01T01:45:00.000','2024-07-01T01:00:00.000','2024-07-15T07:00:00.000', 'LARGE', 'BLACK', (SELECT sc.id FROM sub_category sc WHERE sc.name='Shoes' AND sc.category_id = (SELECT id FROM category c WHERE c.name='Women')), ((SELECT p.id FROM person p WHERE p.email='ahmedinhasanovic2000@gmail.com'))),
                                                                                                                                       ('Second brown man','Note:\nThe Jackets is US standard size, Please choose size as your usual wear\nMaterial: 100% Polyester\nDetachable Liner Fabric: Warm Fleece. Detachable\nFunctional Liner: Skin Friendly, Lightweigt and Warm.\nStand Collar Liner jacket, keep you warm in cold weather.\nZippered Pockets: 2 Zippered Hand Pockets, 2 Zippered Pockets on Chest enough to keep cards or keys) and 1 Hidden Pocket Inside.\nZippered Hand Pockets and Hidden Pocket keep your things secure.\nHumanized Design: Adjustable and Detachable Hood and Adjustable cuff to prevent the wind and water,for a comfortable fit.\n3 in 1 Detachable Design provide more convenience, you can separate the coat and inner as needed, or wear it together. It is suitable for different season and help you adapt to different climates',50,'2024-01-01T01:17:00.000','2024-07-01T01:00:00.000','2024-07-15T06:00:00.000', 'LARGE', 'BLACK', (SELECT sc.id FROM sub_category sc WHERE sc.name='Shoes' AND sc.category_id = (SELECT id FROM category c WHERE c.name='Men')), ((SELECT p.id FROM person p WHERE p.email='ahmedinhasanovic2000@gmail.com'))),
                                                                                                                                       ('Other white casual shoes','Note:\nThe Jackets is US standard size, Please choose size as your usual wear\nMaterial: 100% Polyester\nDetachable Liner Fabric: Warm Fleece. Detachable\nFunctional Liner: Skin Friendly, Lightweigt and Warm.\nStand Collar Liner jacket, keep you warm in cold weather.\nZippered Pockets: 2 Zippered Hand Pockets, 2 Zippered Pockets on Chest enough to keep cards or keys) and 1 Hidden Pocket Inside.\nZippered Hand Pockets and Hidden Pocket keep your things secure.\nHumanized Design: Adjustable and Detachable Hood and Adjustable cuff to prevent the wind and water,for a comfortable fit.\n3 in 1 Detachable Design provide more convenience, you can separate the coat and inner as needed, or wear it together. It is suitable for different season and help you adapt to different climates',50,'2024-01-02T01:00:00.000','2024-07-01T01:00:00.000','2024-07-15T05:00:00.000', 'LARGE', 'BLACK', (SELECT sc.id FROM sub_category sc WHERE sc.name='Shoes' AND sc.category_id = (SELECT id FROM category c WHERE c.name='Women')), ((SELECT p.id FROM person p WHERE p.email='ahmedinhasanovic2000@gmail.com'))),
                                                                                                                                       ('White sport shoes2','Note:\nThe Jackets is US standard size, Please choose size as your usual wear\nMaterial: 100% Polyester\nDetachable Liner Fabric: Warm Fleece. Detachable\nFunctional Liner: Skin Friendly, Lightweigt and Warm.\nStand Collar Liner jacket, keep you warm in cold weather.\nZippered Pockets: 2 Zippered Hand Pockets, 2 Zippered Pockets on Chest enough to keep cards or keys) and 1 Hidden Pocket Inside.\nZippered Hand Pockets and Hidden Pocket keep your things secure.\nHumanized Design: Adjustable and Detachable Hood and Adjustable cuff to prevent the wind and water,for a comfortable fit.\n3 in 1 Detachable Design provide more convenience, you can separate the coat and inner as needed, or wear it together. It is suitable for different season and help you adapt to different climates',50,'2024-01-03T01:00:00.000','2024-07-01T01:00:00.000','2024-07-15T06:30:00.000', 'LARGE', 'BLACK', (SELECT sc.id FROM sub_category sc WHERE sc.name='Shoes' AND sc.category_id = (SELECT id FROM category c WHERE c.name='Women')), ((SELECT p.id FROM person p WHERE p.email='ahmedinhasanovic2000@gmail.com'))),
                                                                                                                                       ('Shoes for occasion3','Note:\nThe Jackets is US standard size, Please choose size as your usual wear\nMaterial: 100% Polyester\nDetachable Liner Fabric: Warm Fleece. Detachable\nFunctional Liner: Skin Friendly, Lightweigt and Warm.\nStand Collar Liner jacket, keep you warm in cold weather.\nZippered Pockets: 2 Zippered Hand Pockets, 2 Zippered Pockets on Chest enough to keep cards or keys) and 1 Hidden Pocket Inside.\nZippered Hand Pockets and Hidden Pocket keep your things secure.\nHumanized Design: Adjustable and Detachable Hood and Adjustable cuff to prevent the wind and water,for a comfortable fit.\n3 in 1 Detachable Design provide more convenience, you can separate the coat and inner as needed, or wear it together. It is suitable for different season and help you adapt to different climates',50,'2024-01-06T01:00:00.000','2024-07-01T01:00:00.000','2024-07-15T03:45:00.000', 'LARGE', 'BLACK', (SELECT sc.id FROM sub_category sc WHERE sc.name='Shoes' AND sc.category_id = (SELECT id FROM category c WHERE c.name='Women')), ((SELECT p.id FROM person p WHERE p.email='ahmedinhasanovic2000@gmail.com'))),
                                                                                                                                       ('Shoes for occasion4','Note:\nThe Jackets is US standard size, Please choose size as your usual wear\nMaterial: 100% Polyester\nDetachable Liner Fabric: Warm Fleece. Detachable\nFunctional Liner: Skin Friendly, Lightweigt and Warm.\nStand Collar Liner jacket, keep you warm in cold weather.\nZippered Pockets: 2 Zippered Hand Pockets, 2 Zippered Pockets on Chest enough to keep cards or keys) and 1 Hidden Pocket Inside.\nZippered Hand Pockets and Hidden Pocket keep your things secure.\nHumanized Design: Adjustable and Detachable Hood and Adjustable cuff to prevent the wind and water,for a comfortable fit.\n3 in 1 Detachable Design provide more convenience, you can separate the coat and inner as needed, or wear it together. It is suitable for different season and help you adapt to different climates',50,'2024-01-04T01:00:00.000','2024-07-01T01:00:00.000','2024-07-15T02:57:00.000', 'LARGE', 'BLACK', (SELECT sc.id FROM sub_category sc WHERE sc.name='Shoes' AND sc.category_id = (SELECT id FROM category c WHERE c.name='Women')), ((SELECT p.id FROM person p WHERE p.email='ahmedinhasanovic2000@gmail.com'))),
                                                                                                                                       ('Shoes with box other','Note:\nThe Jackets is US standard size, Please choose size as your usual wear\nMaterial: 100% Polyester\nDetachable Liner Fabric: Warm Fleece. Detachable\nFunctional Liner: Skin Friendly, Lightweigt and Warm.\nStand Collar Liner jacket, keep you warm in cold weather.\nZippered Pockets: 2 Zippered Hand Pockets, 2 Zippered Pockets on Chest enough to keep cards or keys) and 1 Hidden Pocket Inside.\nZippered Hand Pockets and Hidden Pocket keep your things secure.\nHumanized Design: Adjustable and Detachable Hood and Adjustable cuff to prevent the wind and water,for a comfortable fit.\n3 in 1 Detachable Design provide more convenience, you can separate the coat and inner as needed, or wear it together. It is suitable for different season and help you adapt to different climates',50,'2024-01-07T01:00:00.000','2024-07-01T01:00:00.000','2024-07-15T05:23:00.000', 'LARGE', 'BLACK', (SELECT sc.id FROM sub_category sc WHERE sc.name='Shoes' AND sc.category_id = (SELECT id FROM category c WHERE c.name='Men')), ((SELECT p.id FROM person p WHERE p.email='ahmedinhasanovic2000@gmail.com'))),
                                                                                                                                       ('Sandals other','Note:\nThe Jackets is US standard size, Please choose size as your usual wear\nMaterial: 100% Polyester\nDetachable Liner Fabric: Warm Fleece. Detachable\nFunctional Liner: Skin Friendly, Lightweigt and Warm.\nStand Collar Liner jacket, keep you warm in cold weather.\nZippered Pockets: 2 Zippered Hand Pockets, 2 Zippered Pockets on Chest enough to keep cards or keys) and 1 Hidden Pocket Inside.\nZippered Hand Pockets and Hidden Pocket keep your things secure.\nHumanized Design: Adjustable and Detachable Hood and Adjustable cuff to prevent the wind and water,for a comfortable fit.\n3 in 1 Detachable Design provide more convenience, you can separate the coat and inner as needed, or wear it together. It is suitable for different season and help you adapt to different climates',50,'2024-01-11T01:00:00.000','2024-07-01T01:00:00.000','2024-07-15T08:22:00.000', 'LARGE', 'BLACK', (SELECT sc.id FROM sub_category sc WHERE sc.name='Shoes' AND sc.category_id = (SELECT id FROM category c WHERE c.name='Women')), ((SELECT p.id FROM person p WHERE p.email='ahmedinhasanovic2000@gmail.com'))),
                                                                                                                                       ('BIYLACLESEN Womens 3-in-1 Snowboard Jacket Winter Coats','Note:\nThe Jackets is US standard size, Please choose size as your usual wear\nMaterial: 100% Polyester\nDetachable Liner Fabric: Warm Fleece. Detachable\nFunctional Liner: Skin Friendly, Lightweigt and Warm.\nStand Collar Liner jacket, keep you warm in cold weather.\nZippered Pockets: 2 Zippered Hand Pockets, 2 Zippered Pockets on Chest enough to keep cards or keys) and 1 Hidden Pocket Inside.\nZippered Hand Pockets and Hidden Pocket keep your things secure.\nHumanized Design: Adjustable and Detachable Hood and Adjustable cuff to prevent the wind and water,for a comfortable fit.\n3 in 1 Detachable Design provide more convenience, you can separate the coat and inner as needed, or wear it together. It is suitable for different season and help you adapt to different climates',50,'2024-01-11T01:00:00.000','2024-07-01T01:00:00.000','2024-07-15T08:22:00.000', 'LARGE', 'BLACK', (SELECT sc.id FROM sub_category sc WHERE sc.name='Clothes' AND sc.category_id = (SELECT id FROM category c WHERE c.name='Men')), ((SELECT p.id FROM person p WHERE p.email='ahmedinhasanovic2000@gmail.com')));

-- Insertion of product pictures
INSERT INTO product_picture (name, url, product_id) VALUES
                                                        ('Black-shoes-with-legs.png', 'https://auction-s3-bucket.s3.eu-central-1.amazonaws.com/Black-shoes-with-legs.png', (SELECT p.id FROM product p WHERE p.name='Black shoes with legs')),
                                                        ('Brown-man-shoes.png', 'https://auction-s3-bucket.s3.eu-central-1.amazonaws.com/Brown-man-shoes.png', (SELECT p.id FROM product p WHERE p.name='Brown man shoes')),
                                                        ('White-shoes-purple-interior.png', 'https://auction-s3-bucket.s3.eu-central-1.amazonaws.com/White-shoes-purple-interior.png', (SELECT p.id FROM product p WHERE p.name='White casual shoes')),
                                                        ('White-sport-shoes.png', 'https://auction-s3-bucket.s3.eu-central-1.amazonaws.com/White-sport-shoes.png', (SELECT p.id FROM product p WHERE p.name='White sport shoes')),
                                                        ('Shoes-for-occasion.png', 'https://auction-s3-bucket.s3.eu-central-1.amazonaws.com/Shoes-for-occasion.png', (SELECT p.id FROM product p WHERE p.name='Shoes for occasion')),
                                                        ('Shoes-for-occasion2.png', 'https://auction-s3-bucket.s3.eu-central-1.amazonaws.com/Shoes-for-occasion2.png', (SELECT p.id FROM product p WHERE p.name='Shoes for occasion2')),
                                                        ('Shoes-with-box.png', 'https://auction-s3-bucket.s3.eu-central-1.amazonaws.com/Shoes-with-box.png', (SELECT p.id FROM product p WHERE p.name='Shoes with box')),
                                                        ('Sandals.png', 'https://auction-s3-bucket.s3.eu-central-1.amazonaws.com/Sandals.png', (SELECT p.id FROM product p WHERE p.name='Sandals')),
                                                        ('Black-shoes-with-legs-other.png', 'https://auction-s3-bucket.s3.eu-central-1.amazonaws.com/Black-shoes-with-legs-other.png', (SELECT p.id FROM product p WHERE p.name='Second black shoes')),
                                                        ('Brown-man-shoes-other.png', 'https://auction-s3-bucket.s3.eu-central-1.amazonaws.com/Brown-man-shoes-other.png', (SELECT p.id FROM product p WHERE p.name='Second brown man')),
                                                        ('White-shoes-purple-interior-other.png', 'https://auction-s3-bucket.s3.eu-central-1.amazonaws.com/White-shoes-purple-interior-other.png', (SELECT p.id FROM product p WHERE p.name='Other white casual shoes')),
                                                        ('White-sport-shoes-other.png', 'https://auction-s3-bucket.s3.eu-central-1.amazonaws.com/White-sport-shoes-other.png', (SELECT p.id FROM product p WHERE p.name='White sport shoes2')),
                                                        ('Shoes-for-occasion3.png', 'https://auction-s3-bucket.s3.eu-central-1.amazonaws.com/Shoes-for-occasion3.png', (SELECT p.id FROM product p WHERE p.name='Shoes for occasion3')),
                                                        ('Shoes-for-occasion4.png', 'https://auction-s3-bucket.s3.eu-central-1.amazonaws.com/Shoes-for-occasion4.png', (SELECT p.id FROM product p WHERE p.name='Shoes for occasion4')),
                                                        ('Shoes-with-box-other.png', 'https://auction-s3-bucket.s3.eu-central-1.amazonaws.com/Shoes-with-box-other.png', (SELECT p.id FROM product p WHERE p.name='Shoes with box other')),
                                                        ('Sandals-other.png', 'https://auction-s3-bucket.s3.eu-central-1.amazonaws.com/Sandals-other.png', (SELECT p.id FROM product p WHERE p.name='Sandals other')),
                                                        ('BIYLACLESEN-Womens-3-in-1-Snowboard-Jacket-Winter-Coats-pic1.png', 'https://auction-s3-bucket.s3.eu-central-1.amazonaws.com/BIYLACLESEN-Womens-3-in-1-Snowboard-Jacket-Winter-Coats-pic1.png' , (SELECT p.id FROM product p WHERE p.name='BIYLACLESEN Womens 3-in-1 Snowboard Jacket Winter Coats')),
                                                        ('BIYLACLESEN-Womens-3-in-1-Snowboard-Jacket-Winter-Coats-pic2.png', 'https://auction-s3-bucket.s3.eu-central-1.amazonaws.com/BIYLACLESEN-Womens-3-in-1-Snowboard-Jacket-Winter-Coats-pic2.png', (SELECT p.id FROM product p WHERE p.name='BIYLACLESEN Womens 3-in-1 Snowboard Jacket Winter Coats')),
                                                        ('BIYLACLESEN-Womens-3-in-1-Snowboard-Jacket-Winter-Coats-pic3.png', 'https://auction-s3-bucket.s3.eu-central-1.amazonaws.com/BIYLACLESEN-Womens-3-in-1-Snowboard-Jacket-Winter-Coats-pic3.png' , (SELECT p.id FROM product p WHERE p.name='BIYLACLESEN Womens 3-in-1 Snowboard Jacket Winter Coats')),
                                                        ('BIYLACLESEN-Womens-3-in-1-Snowboard-Jacket-Winter-Coats-pic4.png', 'https://auction-s3-bucket.s3.eu-central-1.amazonaws.com/BIYLACLESEN-Womens-3-in-1-Snowboard-Jacket-Winter-Coats-pic4.png' , (SELECT p.id FROM product p WHERE p.name='BIYLACLESEN Womens 3-in-1 Snowboard Jacket Winter Coats')),
                                                        ('BIYLACLESEN-Womens-3-in-1-Snowboard-Jacket-Winter-Coats-pic5.png', 'https://auction-s3-bucket.s3.eu-central-1.amazonaws.com/BIYLACLESEN-Womens-3-in-1-Snowboard-Jacket-Winter-Coats-pic5.png' , (SELECT p.id FROM product p WHERE p.name='BIYLACLESEN Womens 3-in-1 Snowboard Jacket Winter Coats')),
                                                        ('BIYLACLESEN-Womens-3-in-1-Snowboard-Jacket-Winter-Coats-pic6.png', 'https://auction-s3-bucket.s3.eu-central-1.amazonaws.com/BIYLACLESEN-Womens-3-in-1-Snowboard-Jacket-Winter-Coats-pic6.png' , (SELECT p.id FROM product p WHERE p.name='BIYLACLESEN Womens 3-in-1 Snowboard Jacket Winter Coats'));

insert into bid (amount, user_id, product_id)
values (71.00, 2, 2),
       (72.00, 2, 3),
       (73.00, 2, 4),
       (74.00, 2, 5),
       (75.00, 2, 6);